version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/brosklasse

    steps:
      - add-ssh-keys:
          fingerprints:
            - "12:b8:85:7e:8b:5b:bc:f3:6f:21:65:03:be:76:0e:4a"

      - checkout

#       DEPENDENCIES 
      - restore_cache:
          keys:
          - root-node-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - root-node-

      - run:
          name: Yarn Dependencies
          command: |
            yarn install --ignore-engines
            cd public
            yarn install --ignore-engines

      - save_cache:
          key: root-node-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

#       BUILD 
      - run:
          name: Build backend
          command: |
            yarn run build
      - run:
          name: Build web
          command: |
            yarn run build-ui

#       DEPLOY HEROKU
      - run:
          name: Deploy Heroku
          command: |
            git config --global user.email "mertens.michael@hotmail.com"
            git config --global user.name "Michael Mertens"
            # "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
            git add index.js -f --all
            git add server/*.js -f --all
            git add server/**/*.js -f --all
            git add public/dist -f --all
            git commit -am "Committing build output" || true
            echo 'heroku.com ssh-rsa $HEROKU_SSH_KEY' >> ~/.ssh/known_hosts
            git push $HEROKU_TARGET --force --no-verify
